#:schema ./node_modules/wrangler/config-schema.json

name = "yangchun-comment-be"
main = "src/index.ts"
compatibility_date = "2025-05-08"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[[kv_namespaces]]
binding = "COMMENTS"
id = "<KV_COMMENTS_ID>"
preview_id = "<KV_COMMENTS_PREVIEW_ID>"

[[unsafe.bindings]]
name = "RATE_LIMITER_POST"
type = "ratelimit"
namespace_id = "1000"
simple = { limit = 2, period = 10 } # 2 requests per minute

[[unsafe.bindings]]
name = "RATE_LIMITER_GET"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 20, period = 10 } # 20 requests every 10 seconds

[vars]
MAX_PSEUDONYM_LENGTH = 80
MAX_MSG_LENGTH = 1000
MAX_ALL_SITE_RSS_COMMENTS = 25
# CORS_ORIGIN = "${CORS_ORIGIN}"
# POST_REGEX = "${POST_REGEX}"
HMAC_SECRET_KEY = "${HMAC_SECRET_KEY}"   # Should be set in Secrets
ADMIN_SECRET_KEY = "${ADMIN_SECRET_KEY}" # JWT secret key for admin auth
# ADMIN_USERNAME = "${ADMIN_USERNAME}"     # Admin username
# ADMIN_PASSWORD = "${ADMIN_PASSWORD}"     # Admin password
RSS_SITE_PATH = "${RSS_SITE_PATH}" # RSS feed URL prefix
